name: 'btc_trnsc_project'
version: '1.0.0'
config-version: 2
require-dbt-version: ['>=1.12.0', '<2.0.0']

profile: 'btc_trnsc_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  btc_trnsc_project:
    example:
      +materialized: view